### PR TITLE
Finish up iframe embed feature

### LINKED ISSUE #509: Embed as iframe share option
We've been thinking of making an option to embed the current map view as an `iframe` so that smaller news outlets and sites could pull a customized view directly into their content (I've seen it done with CARTO and Mapbox maps before).

It could exist as an additional option in the share menu, or it could potentially be a sub-option on the share a link popup. Either way, we'd likely need to highlight it somewhere that's more media-focused since I don't imagine people will be looking for that on their own.

We could trigger the `iframe` view with a URL parameter that limits the view, potentially removing most/all controls for changing the map data since the `iframe` will probably be a much smaller size.

### PR DESCRIPTION
**Pull request by pjsier**
Closes #509, since the rest of the functionality is in #568 and #651. Getting pym.js set up was a bit of a pain initially since it sets up query parameters that are swallowed by our hash routing, but after swapping those back in it looks like this will be a lot easier than trying to create an iframe with the right set of parameters

### CODE REVIEW

**Comment by Lane** [comment]
Looks good.  For organization purposes, could we keep the embed related CSS in `embed.component.scss`?

**Comment by Lane** [comment]
actually, it's probably fine for the most part, just looking at `app.component.scss` mostly.  Also, not sure I'm understanding what the `html.embedded, html.not-embedded` rules are doing?  Wouldn't that apply to everything?

**Comment by pjsier** [comment]
That was actually going to be my question, moving it out of `app.component.scss` definitely makes sense since I set that up when I was trying to get it to work, but do the styles in `map.component.scss` still work?

And `embedded`/`not-embedded` are both added by pym.js, they're not any of our host-bindings, but `not-embedded` was only there from testing. It's only applied when activate the pym child, but I'll remove it anyway since we don't need it

**Comment by Lane** [comment]
yep, the styles in `map.component` are fine, but would you be able to put the `app.component` stuff in `embed.component`?

**Comment by pjsier** [comment]
Yep! Updated that in the latest commit

**Comment by Lane** [comment]
I think you maybe moved the stuff from `style.scss` instead?  Still seeing the embed related stuff in `app.component.scss`

**Comment by pjsier** [comment]
Whoops, yeah I got them mixed up. I can make that change tonight

**Comment by pjsier** [comment]
Removed everything except the `display: none` on embed branding, let me know if that works!

**Pull request merged**
