### PR TITLE
Update city labels, null check on tooltip

### LINKED ISSUE #502: Use us-cities-10 source for city labels
City labels are currently being sourced from OpenMapTiles, but that's leading to some weird inconsistencies where mid-sized cities in their data aren't represented in our census information:

screen shot 2018-01-22 at 8 40 39 am

We should be able to switch to using the `us-cities-10` layer and filtering based off of the population as a rough proxy so that labels line up

### PR DESCRIPTION
**Pull request by pjsier**
Closes #502 and #503. Prototype of the changes here http://eviction-lab-prototypes.s3-website.us-east-2.amazonaws.com/city-labels/

### CODE REVIEW

**Comment by pjsier** [comment]
Null check is fixed so this is ready for review

**Comment by Lane** [comment]
Not sure if this is a big deal, but I've noticed some cities also have the county names in them on our `us-cities` source.

image

**Comment by pjsier** [comment]
Yeah, I noticed that too. It's a weird quirk of the census data that some census places are both counties and "cities". I'm good with leaving that as-is, since these labels are more for general orientation, but we could probably filter out the ones that end with county if you think it's confusing

**Comment by Lane** [comment]
It doesn't really bother me, will merge in for now and get some feedback from the team if it's okay as is.

**Pull request merged**
