### PR TITLE
Responsive sidebar

### LINKED ISSUE #580: Ranking Tool Sidebar Component
Ranking tool needs sidebar component that contains the location search, and all of the UI elements (`ranking-ui.component`) for manipulating the current view.

**Mobile**
  - Sidebar can be toggled on / off with search & filter button
  - Sidebar fills viewport

**Tablet**
  - Sidebar can be toggled on / off with search & filter button that is fixed to the left side of the screen
  - Sidebar slides in from left and overlaps ranking list

**Desktop**
  - Sidebar displays on the left side of the ranking list
  - Sidebar is sticky as the page scrolls (when vertical space permits)

### PR DESCRIPTION
**Pull request by Lane**
- Adds "Search & Filter" button on mobile that shows pulls out the UI panel over the page
- Moves "Search & Filter" button as a sticky element on the side of the page that opens the UI panel when pressed, scrolls with page.

Closes #580 

Tablet:
sidebar-tablet

Mobile:
sidebar-mobile

### CODE REVIEW

**Comment by pjsier** [comment]
Some of the dropdowns are getting clipped for me on tablet

screen shot 2018-02-12 at 2 57 50 pm

**Comment by Lane** [comment]
Whoops, should be good now.

**Comment by pjsier** [comment]
I'm not sure how this is happening, but the mini-border for the `::after` pseudo-element in the nav bar is showing up halfway down the page on mobile screen sizes (in Firefox)

screen shot 2018-02-12 at 3 06 23 pm

**Comment by Lane** [comment]
Yeah, lots of styles are off for mobile.  Was going to fix up in a separate PR, but just pushed a commit to fix that here.

**Comment by pjsier** [comment]
Gotcha, wasn't sure what should be fixed here vs. a separate PR, but that covers everything from my end! Merging

**Pull request merged**
