### PR TITLE
Restrict layers by zoom level

### PR DESCRIPTION
**Pull request by pjsier**
Updated version of #68. `MapLayerGroup`s now have a `minzoom` property that sets the minimum zoom level for them to be displayed. If a layer with `minzoom` is being viewed, and the users zooms out past the `minzoom`, auto switching of layers is turned back on to handle the currently displayed layer.

### CODE REVIEW

**Comment by Lane** [comment]
Great!  I have a few updates for this one:

  - Should we show all of the levels in the select, and just grey out the ones that are unavailable at the current zoom level?  I wouldn't want someone top open that menu zoomed out, and think that states / counties are the only available options.
  - I think the zoom levels might need adjusting?  I zoomed it and selected block groups, but the outlines were showing me census tracts.  Example below:

Image

**Comment by pjsier** [comment]
Agreed about graying out, but I'd also want to check with Abby on that because I think she preferred not displaying them at all. And for the census tracts, I think that's just the full label for block groups, so the name is TRACT.1, Census Tract TRACT

**Comment by Lane** [comment]
Ah, makes sense!  Should we keep a small border at the lower zoom levels?  If there is no choropleth highlighting, you can really tell the boundaries that the circles represent.

**Comment by pjsier** [comment]
Hmm, I could go either way on keeping a border. On the one hand it could be confusing, but on the other hand the borders will be for the aggregated geometries, and now that we're restricting the zoom levels the layers won't be visible at all for a larger portion of the map. Maybe we could also consider some way of making it more apparent which layer you're on?

**Pull request merged**
